package com.gesturecontacts.ui.theme

import androidx.compose.ui.graphics.Color

// Light colors
val md_theme_light_primary = Color(0xFF0061A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD7E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D3C)
val md_theme_light_secondary = Color(0xFF535F7D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1B37)
val md_theme_light_tertiary = Color(0xFF6D5676)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF7D8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF28132F)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)

// Dark colors
val md_theme_dark_primary = Color(0xFFAAC7FF)
val md_theme_dark_onPrimary = Color(0xFF003062)
val md_theme_dark_primaryContainer = Color(0xFF004687)
val md_theme_dark_onPrimaryContainer = Color(0xFFD7E7FF)
val md_theme_dark_secondary = Color(0xFFBDC7FF)
val md_theme_dark_onSecondary = Color(0xFF233050)
val md_theme_dark_secondaryContainer = Color(0xFF3A4668)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_tertiary = Color(0xFFDBADFF)
val md_theme_dark_onTertiary = Color(0xFF422A47)
val md_theme_dark_tertiaryContainer = Color(0xFF5A3F5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFF7D8FF)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
